tutoria/authentication/urls.py
"""
authentication/urls.py

Created on Oct. 23, 2017
by Jiayao
"""
from django.urls import reverse_lazy
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'auth'

urlpatterns = [
      url(r'^$', views.IndexView.as_view(), name='signup'),
      url(r'^profile/$', views.ProfileView.as_view(), name='profile'),
      url(r'^student/$', views.StudentView.as_view(), name='student'),
      url(r'^tutor/$', views.TutorView.as_view(), name='tutor'),
      url(r'^both/$', views.BothView.as_view(), name='both'),
      url(r'^login/$', views.LoginView.as_view(), name='login'),
      url(r'^logout/$', views.logout_view, name='logout'),
      url(r'^reset/$', lambda req, **kwargs: auth_views.password_reset(
        req, template_name='form.html',
        from_email=views.PASSWORD_EMAIL_SENDER,
        email_template_name='reset_password_email.html',
        post_reset_redirect=reverse_lazy('auth:password_reset_done'),
        extra_context={
            'validlink': True,
            'form_title': 'Forgot Password',
            'form_submit': 'Retreive Password',
        }, **kwargs
        ), name='password_reset'),
      url(r'^reset/retreive/$', lambda req, **kwargs: auth_views.password_reset_done(
        req, template_name='message.html',
        # post_reset_redirect='auth.password_reset_done',
        extra_context={
            'message_title': 'Forgot Password',
            'message_content': views.PASSWORD_RESET_DONE_MSG,
        }, **kwargs
        ), name='password_reset_done'),
      url(views.PASSWORD_RESET_TOKEN_REGEX, lambda req, **kwargs: auth_views.password_reset_confirm(
              req, template_name='form.html',
              post_reset_redirect=reverse_lazy('auth:password_reset_complete'),
              extra_context={
                  'form_title': 'Reset Password',
                  'form_submit': 'Reset',
                  'exception_msg': views.PASSWORD_RESET_EX_MSG,
              }, **kwargs
          ), name='password_reset_confirm'),
      url(r'^reset/done/$', lambda req, **kwargs: auth_views.password_reset_complete(  # Ignore PycodestyleBear (E501)
          req, template_name='message.html',
          extra_context={
              'message_title': 'Reset Password',
              'message_content': views.PASSWORD_RESET_COMPLETE,
          }, **kwargs
      ), name='password_reset_complete'),

]

tutoria/dashboard/urls.py
from django.conf.urls import url

from . import views

app_name = 'dashboard'

urlpatterns = [
    url(r'mybookings/$', views.MybookingsView.as_view(), name='mybookings'),
    url(r'mytransactions/$', views.MytransactionsView.as_view(), name='mytransactions'),
    url(r'mytimetable/$', views.MytimetableView.as_view(), name='mytimetable'),
    url(r'mywallet/$', views.MyWalletView.as_view(), name='mywallet'),
]

tutoria/search/urls.py
from django.conf.urls import url

from . import views

app_name = 'search'

urlpatterns = [
    url(r'result/$', views.ResultView.as_view(), name='result'),
    url(r'^$', views.IndexView.as_view(), name='index'),
]

tutoria/tutor/urls.py
'""URL Mapping.""'

from django.conf.urls import url
from . import views

app_name = 'tutor'

urlpatterns = [
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<tutor_id>[0-9]+)/book/$',
        views.confirm_booking, name='confirm_booking'),
    url(r'^(?P<tutor_id>[0-9]+)/book/confirm$',
        views.save_booking, name='save_booking'),
    url(r'^(?P<tutor_id>[0-9]+)/review$',
        views.ReviewView.as_view(), name='review'),
]

tutoria/tutoria/urls.py
from __future__ import (absolute_import, print_function)
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^$', views.IndexView.as_view(), name='homepage'),
    url(r'^search/', include('search.urls', namespace='search'), name='search'),
    url(r'^tutor/', include('tutor.urls', namespace='tutor'), name='tutor'),
    # app_name: authentication namespace: auth
    url(r'^auth/', include('authentication.urls', namespace='auth'), name='auth'),
    url(r'^api/keywords/', views.get_keywords, name='get_keywords'),
    url(r'^dashboard/', include('dashboard.urls',
                                namespace='dashboard'), name='dashboard'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tutoria/search/models.py
# Create your models here.

tutoria/search/views.py
'""View for search results.""'
from django.views.generic import ListView, TemplateView
import re  # Regular expression for search matching
from django.db.models import Max

from account.models import Tutor
from scheduler.models import Session

from datetime import datetime, timedelta


class IndexView(TemplateView):
    '""Render the search page.""'

    template_name = 'search.html'
    context_object_name = 'index_context'


class ResultView(ListView):
    '""View for search results.""'

    template_name = 'result.html'
    model = Tutor
    sort_method = 'rating'  # Sort by rating by default
    keywords = ''
    minPrice = 0  # Integer. Minimum hourly rate.
    price_limit = 1000
    maxPrice = 500  # Integer. Maximum hourly rate.
    tutor_type = 'ALL'
    # Only show tutor with available session in the coming 7 days?
    only_show_available = False

    def dispatch(self, request, *args, **kwargs):
        self.price_limit = list(Tutor.objects.all().aggregate(
            Max('hourly_rate')).values())[0]
        self.maxPrice = self.price_limit
        return super(ResultView, self).dispatch(request, *args, **kwargs)

    def get_queryset(self):
        '""Determine the list of tutors to be displayed.""'
        if 'keywords' in self.request.GET:
            self.keywords = self.request.GET['keywords']
        if 'sort' in self.request.GET:
            self.sort_method = self.request.GET['sort']
        if 'minPrice' in self.request.GET:
            self.minPrice = int(re.sub('\D', '', self.request.GET['minPrice']))
        if 'maxPrice' in self.request.GET:
            self.maxPrice = int(re.sub('\D', '', self.request.GET['maxPrice']))
        if 'tutor_type' in self.request.GET:
            self.tutor_type = self.request.GET['tutor_type']
        if 'only_show_available' in self.request.GET:
            self.only_show_available = eval(
                self.request.GET['only_show_available'])
        if 'price_limit' in self.request.GET:
            self.price_limit = self.request.GET['price_limit']

        all_tutors = Tutor.objects.filter(visible=True)  # Obtain visible tutors
        filtered_tutors = []
        if len(self.keywords) == 0:
            filtered_tutors = all_tutors
        else:
            # Filter according to keywords
            for tutor in all_tutors:
                # Search query in full name
                tutor_info = tutor.full_name
                # Search query in courses
                for course in tutor.courses.all():
                    tutor_info += (' ' + str(course))
                # Search query in tags
                for tag in tutor.tags.all():
                    tutor_info += (' ' + str(tag))
                # Search query in university
                tutor_info += (' ' + tutor.university)
                # Regular expression match
                for keyword in self.keywords.split():
                    if re.search(keyword, tutor_info, re.IGNORECASE) and tutor not in filtered_tutors:  # Ignore PycodestyleBear (E501)
                        filtered_tutors.append(tutor)
        # Filter according to hourly rate range.
        filtered_tutors = [t for t in filtered_tutors if
                           self.minPrice <= t.hourly_rate <= self.maxPrice]
        # Filter according to tutor type
        if self.tutor_type != 'ALL':
            filtered_tutors = [
                t for t in filtered_tutors if t.tutor_type == self.tutor_type]
        if self.only_show_available:
            filtered_tutors = [t for t in filtered_tutors if tutor_available(t)]
        # Sort tutors
        if self.sort_method == 'hourly_rate_inc':
            return sorted(filtered_tutors, key=lambda x: x.hourly_rate, reverse=False)  # Ignore PycodestyleBear (E501)
        if self.sort_method == 'hourly_rate_dec':
            return sorted(filtered_tutors, key=lambda x: x.hourly_rate, reverse=True)  # Ignore PycodestyleBear (E501)
        return sorted(filtered_tutors, key=lambda x: x.avgRating, reverse=True)

    def get_context_data(self, **kwargs):
        '""Obtain search query keywords from GET request.""'
        context = super(ResultView, self).get_context_data(**kwargs)
        if 'keywords' in self.request.GET:
            context['keywords'] = self.request.GET['keywords']
        else:
            context['keywords'] = self.keywords
        # print('keywords ==> ' + context['keywords'])
        context['sort'] = self.sort_method
        context['minPrice'] = self.minPrice
        context['tutor_type'] = self.tutor_type
        context['only_show_available'] = self.only_show_available
        context['price_limit'] = self.price_limit
        context['maxPrice'] = self.maxPrice
        return context


def tutor_available(tutor):
    '""Test if tutor has any available session in the coming 7 days.""'
    today_min = datetime.combine(datetime.today(), datetime.min.time())
    future_max = datetime.combine(
        datetime.today() + timedelta(7), datetime.max.time())
    available_sessions = Session.objects.filter(tutor=tutor, status='A', start_time__gte=today_min,  # Ignore PycodestyleBear (E501)
                                                end_time__lte=future_max)
    return available_sessions.count() > 0

tutoria/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <!--[if lt IE 9]>
			<script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			<script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->
    {% block header %}{% endblock %}
</head>
<body>
<!--Here is the navbar-->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#navbar-collapse-basepage">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{% url 'homepage' %}" class="navbar-brand">Tutoria</a>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse-basepage">
            <ul class="nav navbar-nav">
              <li id="homepage"><a href="{% url 'search:index' %}">Search</a></li>
                <!--
                    <li id="add_book"><a href=""></a></li>
                -->
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
									{% if user.is_superuser %}
                    <li><a href="{% url 'auth:logout' %}">Logout</a></li>
									{% elif user.is_staff %}
                    <li><a href="{% url 'dashboard:mywallet' %}">My Wallet</a></li>
                    <li><a href="{% url 'auth:logout' %}">Logout</a></li>
									{% else %}
                    <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Dashboard<span class="caret"></span></a>
                     <ul class="dropdown-menu">
                       <li><a href="{% url 'dashboard:mybookings' %}">My Bookings</a></li>
                       <li><a href="{% url 'dashboard:mytransactions' %}">My Transactions</a></li>
                       <li><a href="{% url 'dashboard:mytimetable' %}">My Timetable</a></li>
                       <li><a href="{% url 'dashboard:mywallet' %}">My Wallet</a></li>
                     </ul>
                    </li>

                    <li><a href="{% url 'auth:profile' %}">Profile</a></li>
                    <li><a href="{% url 'auth:logout' %}">Logout</a></li>
									{% endif %}
                {% else %}
                    <li><a href="{% url 'auth:signup' %}">Sign Up</a></li>
                    <li><a href="{% url 'auth:login' %}">Login</a></li>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>
<!-- /nav -->
<!-- header -->
<header class="jumbotron subhead" id="header-base">
    <div class="container">
        <h1>Tutoria</h1>
    </div>
</header>
<!-- /.header -->
<!-- main part -->
{% block content %}{% endblock %}
<!-- /.main -->

<!-- footer -->
<footer class="footer" role="contentinfo">
    <hr>
    <div class="container">
        <p class="text-center"><strong>Hola Inc.</strong></p>
        <p class="text-center">© 2017 All rights reserved</p>
        <h5 class="text-center"> Powered by&nbsp;<a
            href="https://www.djangoproject.com/">Django</a></h5>
    </div>
</footer>
<!-- /.footer-->
<script type="text/javascript">
    $('#{{active_menu}}').addClass("active");
</script>
{% block js %}{% endblock %}
</body>
</html>

tutoria/templates/book.html
{% extends "base.html" %} {% load staticfiles %} {% block title %}Book Session{% endblock %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-offset-4 col-md-4">
      <h1>Confirm Booking</h1>
      <h3>Session</h3>
      <p>{{ session.start_time }} - {{ session.end_time }}</p>
      <h3>Tutor</h3>
      <p>
        {{ tutor.first_name }} {{ tutor.last_name }}
      </p>
      <h3>Tag</h3> {% for tag in tutor.tags.all %}
      <p>{{ tag.tag }}</p> {% endfor %}
      <h3>Course</h3> {% for course in tutor.courses.all %}
      <p>{{ course.course_code }}</p> {% endfor %}
    </div>
    <div class="col-md-offset-4 col-md-4">
      <h3>Fee: ${{tutor.hourly_rate}}</h3>
      <h3>Commission: ${{commission}}</h4>
      <h2><strong>Total: ${{total}}</strong></h2>
      <h3>Balance: ${{balance}}</h3>
    </div>
  </div>

  <hr style="width: 50%; color: grey; height: 1px; background-color:grey;" />

  <div class="row">
    <div class="col-md-offset-4 col-md-4">
      <input id="coupon_checkbox" name="coupon_checkbox" type="checkbox" value="coupon" onclick="var input = document.getElementById('coupon_input'); if(this.checked){ input.disabled = false; input.focus();}else{input.disabled=true;}" />
      <label for="coupon_checkbox">Use Coupon</label>
      <input type="text" id="coupon_input" name="coupon_input_field" disabled="disabled" />
    </div>
  </div>
  <div class="row">
    <div class="col-md-offset-5 col-md-4">
      <form action="{% url 'tutor:save_booking' tutor_id=tutor.id %}" method="POST" role="form" class="form-horizontal">
        {% csrf_token %}
        <button name="session_id" type="submit" onclick="return confirm('Email Sent!')" value="{{ session.id }}" class="btn btn-default">Confirm Booking</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}

tutoria/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Tutoria{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
					{% if not user.is_authenticated %}
					<h1><b>You just found Tutoria.</b></h1><br>
					<h3>Tutoria is an online platform for free/private
						campus tutoring.</h3>
					<h3><a href='{% url 'auth:signup' %}'>Sign up</a>
						or begin a <a href='{% url 'search:index' %}'>search</a> to start. </h3>
					<h5><i>Already sign up? <a href='{% url 'auth:login'%}'>Login</a> to evolve with Tutoria.</i></h5>
					{% else %}
					<h2>Tutoria welcomes you back, {{ user.first_name }}!</h2>
					{% endif %}
        </div>
    </div>

{% endblock %}

tutoria/templates/my_timetable.html
{% extends "base.html" %} {% load staticfiles %} {% block title %}Tutoria{% endblock %} {% block content %}
    <div class="container">
        {% if is_tutor == True %}
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <h3>Tutor Timetable</h3>
                Pattern:&nbsp; 
                <button type="button" class="bg-primary" onclick="return confirm('Click on booked slot to see detail')">Booked</button>&nbsp;
                <button type="button" class="bg-success" onclick="return confirm('Click on bookable slot to close')">Bookable</button>&nbsp;
                <button type="button" class="bg-info" onclick="return confirm('Click on closed slot to open')">Closed</button>&nbsp;
                <button type="button" class="bg-danger" onclick="return confirm('Passed slot means the specific time slot has passed')">Passed</button>
                <br />
                <table class="" border="1" cellpadding="0">
                    <tbody>
                        <tr>
                            <td>Tutor Table</td>
                            {% for i in "xxxxxxxxxxxxxxxxxxxxxxxx" %}
                            {% if tutor.tutor_type == 'PT' %}
                            <td colspan="1">
                            {% else %}
                            <td colspan="2">
                            {% endif %}
                            {% if forloop.counter0 < 10 %}
                                0{{ forloop.counter0 }}:00
                            {% else %}
                                {{ forloop.counter0 }}:00
                            {% endif %}
                            </td>
                            {% endfor %}
                        </tr>
                        {% for grid in tutor_timetable %}
                        {% if tutor.tutor_type == 'PT' and forloop.counter0|divisibleby:24 or tutor.tutor_type == 'CT' and forloop.counter0|divisibleby:48 %}
                        <tr class="slots">
                            <td class="resourcename">
                                {{ grid.date }}
                            </td>
                        {% endif %}
                        {% if grid.status == 'A' %}
                            <td colspan="1" class="bg-success">
                                <form id="book-{{ grid.id }}" method="post" action="{% url 'dashboard:mytimetable' %}" style="cursor:pointer">
                                {% csrf_token %}
                                <div onclick="document.getElementById('book-{{ grid.id }}').submit();">
                                    <input type="hidden" name="session_id" value="{{ grid.id }}">&nbsp;
                                </div>
                                </form>
                            </td>
                        {% elif grid.status == 'B' %}
                            <td colspan="1" class="bg-primary">
                                <form id="book-{{ grid.id }}" method="get" action="{% url 'dashboard:mybookings' %}" style="cursor:pointer">
                                <div onclick="document.getElementById('book-{{ grid.id }}').submit();">
                                    <input type="hidden" name="id" value="{{ grid.id }}">&nbsp;
                                </div>
                                </form>
                            </td>

                        {% elif grid.status == 'X' %}
                            <td colspan="1" class="bg-info">
                                <form id="book-{{ grid.id }}" method="post" action="{% url 'dashboard:mytimetable' %}" style="cursor:pointer">
                                {% csrf_token %}
                                <div onclick="document.getElementById('book-{{ grid.id }}').submit();">
                                    <input type="hidden" name="session_id" value="{{ grid.id }}">&nbsp;
                                </div>
                                </form>
                            </td>

                        {% elif grid.status == 'PASSED' %}
                            <td colspan="1" class="bg-danger">&nbsp;
                            </td>

                        {% endif %}
                        {% if tutor.tutor_type == 'PT' and forloop.counter|divisibleby:24 or tutor.tutor_type == 'CT' and forloop.counter|divisibleby:48 %}
                        </tr>
                        {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% endif %}

        {% if is_student == True %}
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <h3>Student Timetable</h3>
                Pattern:&nbsp; 
                <button type="button" class="bg-success" onclick="return confirm('Click on booked slot to see detail')">Booked</button>&nbsp;
                <button type="button" class="bg-info" onclick="return confirm('Free slot means you have no booking at that time')">Free</button>&nbsp;
                <button type="button" class="bg-danger" onclick="return confirm('Passed slot means the specific time slot has passed')">Passed</button>
                <table class="" border="1" cellpadding="0">
                    <tbody>
                        <tr>
                            <td>Student Table</td>
                            {% for i in "xxxxxxxxxxxxxxxxxxxxxxxx" %}
                            <td colspan="2">
                            {% if forloop.counter0 < 10 %}
                                0{{ forloop.counter0 }}:00
                            {% else %}
                                {{ forloop.counter0 }}:00
                            {% endif %}
                            </td>
                            {% endfor %}
                        </tr>
                        {% for grid in student_timetable %}
                        {% if forloop.counter0|divisibleby:48 %}
                        <tr class="slots">
                            <td class="resourcename">
                                {{ grid.date }}
                            </td>
                        {% endif %}
                        {% if grid.status == 'A' %}
                            <td colspan="1" class="bg-success">
                                <form id="book-{{ grid.id }}" method="get" action="{% url 'dashboard:mybookings' %}" style="cursor:pointer">
                                <div onclick="document.getElementById('book-{{ grid.id }}').submit();">
                                    <input type="hidden" name="id" value="{{ grid.id }}">&nbsp;
                                </div>
                                </form>
                            </td>
                        {% elif grid.status == 'PASSED' %}
                            <td colspan="1" class="bg-danger">&nbsp;
                            </td>
                        {% else %}
                            <td colspan="1" class="bg-info">
                                <input type="hidden" name="id" value="{{ grid.id }}">&nbsp;
                            </td>

                        {% endif %}
                        {% if forloop.counter|divisibleby:48 %}
                        </tr>
                        {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        {% endif %}

    </div>
  {% endblock %}

tutoria/templates/my_transactions.html
{% extends "base.html" %} {% load staticfiles %} {% block title %}Tutoria{% endblock %} {% block content %}
{% if not_logged_in == 'true' %}
   <center><h2>Please Log In First!</h2></center>
{% else %}



{% if records is not None %}
<div class="container">
  <div class="row">
    <div class="col-md-11 col-md-offset-1">
      <div class="col-md-11">

        <th><a href="{% url 'dashboard:mywallet' %}"><center><h2>Current Balance:   {{balance}}</h2></center></a></th>
        <th><h2> </h2></th>
        <table class="table table-hover" width="80%">
          <thead>
            <tr>
              <th>#</th>
              <th>Transaction type</th>
              <th>Transaction with</th>
              <th>Session Type</th>
              <th>Session start time</th>
              <th>Session end time</th>
              <th>Transaction time</th>
              <th>Amount</th>
              <th>Commission</th>
              <th>Status</th>
            </tr>
          </thead>
          <tbody>
            {% for record, transaction in zipped %}
            <tr>
              <td>{{forloop.counter}}</td>
              
              <td>
                {% if username == record.student.username %}Paid to{% else %}Received from{% endif %}
              </td>
              <td>
                 {% if username == record.student.username %}
                <center>
                  <a href="{% url 'tutor:detail' record.tutor.id %}">{{ record.tutor.first_name }}
                                      {{record.tutor.last_name }}</a>
                </center>
                {% else %}
                {{ record.student.first_name }} {{ record.student.last_name }}
                {% endif %}
              </td>
              <td>
                {% if record.tutor.tutor_type == 'CT' %} Contracted Tutoring {% else %} Private Tutoring {% endif %}
              </td>

              <td>{{record.session.start_time}}</td>
              <td>{{record.session.end_time}}</td>
              <td>{{transaction.created_at}}</td>
              <td>{{transaction.amount }}</td>
              <td>{{transaction.commission }}</td>
              <td> {% if record.status == 'F' %}Completed{% elif record.status == 'C' %} {% if user_type == 'Student' %}Refunded{% else %} Canceled {% endif %}{% else %} {% if user_type == 'Student' %}Paid{% else %}Pending completion{% endif %}{% endif %}
              </td>

            </tr>
            {% empty %}
            <tr>
              <td>No transactions found =(</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

      </div>
    </div>
  </div>
</div>

{% else %}

<h3> No transactions found.</h3> {% endif %}{% endif %} {% endblock %}

tutoria/templates/search.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Tutoria{% endblock %}

{% block content %}

  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 well">
        <h2>&emsp;&emsp;Search</h2>
        <form action="{% url 'search:result' %}" id="search" method="GET" role="form" class="form-horizontal">
          <div class="form-group">
            <div class="col-md-12">
              <input type="text" class="form-control" name="keywords"
                     autofocus placeholder="Tutor Name / University / Course / Subject Tag">
            </div>
          </div>
        </form>
        <div class="col-md-12"><br></div>
        <div class="col-md-12">
          <div style="text-align: center">
            <button type="submit" class="btn btn-primary" form="search" value="Submit" style="margin: auto;">Search</button>
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}
{% block js %}
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js" type="text/javascript"></script>
  <script type="text/javascript">
    $(function() {
      $("input[name='keywords']").autocomplete({
        source: "{% url 'get_keywords' %}",
        minLength: 2,
      });
    });

  </script>
{% endblock %}

tutoria/templates/signup.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Tutoria{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
              <h1 class="form-signin-heading text-center">Sign Up</h1>
              {% if status == SIGNUP_STATUS.SUCCESS %}
                <h5> Sign-up successful </h5>
              {% elif status == SIGNUP_STATUS.FAILED %}
                <h5> Sign-up failed </h5>
              {% elif status == SIGNUP_STATUS.EXISTED %}
                <h5> User existed </h5>

              {% else %}
                {% if choice %}
                <form action="{% url 'auth:student' %}" class="form-horizontal">

                    <div class="form-group">
                      <div class="col-md-4 col-md-offset-4">
                        <button class="btn btn btn-primary btn-block" type="submit" id="">I am A Student</button>
                      </div>
                    </div>
                </form>

                <form action="{% url 'auth:tutor' %}" class="form-horizontal">
                    <div class="form-group">
                      <div class="col-md-4 col-md-offset-4">
                        <button class="btn btn btn-primary btn-block" type="submit" id="">I am A Tutor</button>
                      </div>
                    </div>
                </form>

                <form action="{% url 'auth:both' %}" class="form-horizontal">
                    <div class="form-group">
                      <div class="col-md-4 col-md-offset-4">
                        <button class="btn btn btn-primary btn-block" type="submit" id="">I am Both</button>
                      </div>
                    </div>
                </form>

                {% else %}
                  {% if user_form is not None %}

                 <form method="POST" role="form" class="form-horizontal">
                    {% csrf_token %}

                    <div class="form-group">
                      <div class="col-md-9">
                        <table>
                          {{ user_form.as_p }}
                          {% if tutor_form is not None %}
                            {{tutor_form.as_p}}
                          {% endif %}
                        </table>
                      </div>
                    </div>

                    <div class="form-group">
                      <div class="col-md-4 col-md-offset-4">
                        <button class="btn btn btn-primary btn-block" type="submit" id="submit">Sign Up</button>
                      </div>
                    </div>
                </form>

                {% endif %}
              {% endif %}
            {% endif %}
           </div>
        </div>
    </div>

{% endblock %}

{% block js %}
{% if tutor_form is not None %}
	<script type="text/javascript">

  function set_hourly_rate_visibility(visible=false) {
    if(visible) {
      $('#id_tutor_form-hourly_rate').show();
      $('label[for="id_tutor_form-hourly_rate"]').show();
    } else {
      $('#id_tutor_form-hourly_rate').hide();
      $('label[for="id_tutor_form-hourly_rate"]').hide();
    }
  }

  $(document).ready(function() {
    set_hourly_rate_visibility(false);
    $('input:radio[name="tutor_form-tutor_type"]').change(function(){
      set_hourly_rate_visibility($('#id_tutor_form-tutor_type_1').prop('checked'));
    });
  });

	</script>
{% endif %}
{% endblock %}